name: train-env
description: Example AML environment
image: mcr.microsoft.com/azureml/base:latest
condaDependenciesFile: environment.yml
python:
  userManagedDependencies: false
  interpreterPath: python
  condaDependencies:
    channels:
      - conda-forge
    dependencies:
      - python=3.10
      - pip:
          - -r file:requirements.txt
