# conda env create -f train-conda.yml
# conda remove -n train-env --all -y
name: train-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip:
      - mlflow==2.15.0
      - azureml-core
      - azureml-dataprep
      - azureml-dataset-runtime
      - dask==2023.12.1
      - fastapi<0.100
      - feast==0.34.1
      - joblib==1.3.2
      - lightgbm==4.3.0
      - matplotlib==3.8.2
      - kds==0.1.3
      - numpy==1.24.4
      - optuna==3.5.0
      - optuna_distributed==0.6.1
      - pandas==1.5.3
      - plotly==5.18.0
      - polars==0.20.10
      - pytest==7.4.4
      - python-dotenv==1.0.1
      - PyYAML==6.0.1
      - scikit-learn==1.3.2
      - scipy==1.11.4
      - seaborn==0.13.2
      - ucimlrepo==0.0.3
      - xgboost==2.0.3
