description: default config for feature store
logger:
  entity: adeemy
  project: diabetes-prediction

data:
  params:
    uci_raw_data_num: 891
    raw_dataset_source: "Bena345/cdc-diabetes-health-indicators"
    pk_col_name: "ID"
    class_col_name: "Diabetes_binary"
    pos_class: "Diabetic"
    date_col_names: []
    datetime_col_names: []
    event_timestamp_col_name: "event_timestamp"
    num_col_names:
      - BMI
      - PhysHlth
    cat_col_names:
      - Age
      - HighBP
      - HighChol
      - CholCheck
      - Smoker
      - Stroke
      - HeartDiseaseorAttack
      - PhysActivity
      - Fruits
      - Veggies
      - HvyAlcoholConsump
      - AnyHealthcare
      - NoDocbcCost
      - GenHlth
      - MentHlth
      - DiffWalk
      - Sex
      - Education
      - Income

files:
  params:
    raw_dataset_file_name: "raw_dataset.parquet"
    inference_set_file_name: "inference.parquet"
    preprocessed_dataset_features_file_name: "preprocessed_dataset_features.parquet" # For feature store
    preprocessed_dataset_target_file_name: "preprocessed_dataset_target.parquet" # For feature store
