$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
experiment_name: training-experiment
code: ../../
command: >-
  sh -c "make setup_feast &&
         make split_data &&
         make train &&
         make evaluate"
environment: azureml:train-env:11
compute: azureml:trainComputeCluster
