$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
experiment_name: training-experiment
code: ./src
command: >-
  python src/training/train.py
  --config_yaml_path src/config/training-config.yml
  --logger_path src/config/logging.conf
environment:
  name: train-env
  version: 11
  conda_file: src/training/train-env.yml
compute:
  target: local #azureml:trainComputeCluster
# inputs:
#   your_input_name:
#     type: uri_folder
#     path: azureml:your-dataset-name@latest  # Specify your input dataset
# outputs:
#   your_output_name:
#     type: uri_folder
#     path: azureml://datastores/workspaceblobstore/paths/your/output/path  # Specify your output path
