$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
experiment_name: training-experiment
description: "Training job for the model"  # Add your description here
tags:  # Add your tags here
  Task_Type: "Classification"
  Classes_No: "Two"
code: ../../
command: >-
  sh -c "make get_init_data &&
         make prep_data &&
         make split_data &&
         make train &&
         make evaluate"
environment: azureml:train-env:63
compute: azureml:trainComputeCluster
