$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
experiment_name: training-experiment
code: ../
command: >-
  python training/train.py
  --config_yaml_path config/training-config.yml
  --logger_path config/logging.conf
environment: azureml:train-env:11
compute: azureml:trainComputeCluster
