name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Run workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      # Checks-out repository under $GITHUB_WORKSPACE, so the job can access it
      # Use cache action to cache the virtual environment (https://stackoverflow.com/a/62639424)
      - uses: actions/checkout@v3

      - name: Set up Python 3.10.*
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.*

      - name: Get pip cache dir
        id: pip-cache
        run: echo "PIP_CACHE_DIR=$(pip cache dir)" >> $GITHUB_ENV

      # Use cache action to cache the virtual environment
      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ${{ env.PIP_CACHE_DIR }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          make install

      - name: Add project path to sys.path
        run: |
          echo "PYTHONPATH=${{github.workspace}}" >> $GITHUB_ENV

      - name: Sort imports with isort
        run: |
          make isort

      - name: Format with black
        run: |
          make format

      - name: Test with pytest
        run: |
          make test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: Adeemy/end-to-end-ml

      - name: Lint with pylint
        run: |
          make lint