# Train model, evaluate and test champion model, build containerized model, and deploy model
name: Eval-Build

on:
  workflow_dispatch:
    # schedule:
    #   - cron: '00 4 * * *' # Runs at 4:00 AM UTC every day

jobs:
  evaluate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10.*
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.*
      - name: Get pip cache dir
        id: pip-cache
        run: echo "PIP_CACHE_DIR=$(pip cache dir)" >> $GITHUB_ENV

      # Use cache action to cache the virtual environment
      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ${{ env.PIP_CACHE_DIR }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          make install

      - name: Add project path to sys.path
        run: |
          echo "PYTHONPATH=${{github.workspace}}" >> $GITHUB_ENV

      # The latest version of the champion model is pulled from model registry
      # and evaluated in this step. If the model performance meets the deployment
      # criteria, the model is then packaged in the build job to deployed in the
      # production environment.
      - name: Evaluate models
        env:
          COMET_API_KEY: ${{ secrets.COMET_API_KEY }}
        run: |
          make evaluate

      - name: Test champion model
        env:
          COMET_API_KEY: ${{ secrets.COMET_API_KEY }}
        run: |
          make test_model

  build:
    runs-on: ubuntu-latest
    needs: evaluate

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Login using same GitHub Actions credentials
      - name: Log in to GitHub container registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      # Ensures that repo name is lowercase, which is a requirement for publishing to ghcr.io
      - name: Lowercase the repo name and username
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/${{ env.REPO }}:${{ github.sha }}
          file: ./src/inference/Dockerfile
