$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
experiment_name: training-experiment
code:
  local_path: ./src/training/train.py # Ensure this path is correct
command: >-
  python train.py
  --config_yaml_path ./src/config/training-config.yml
  --logger_path ./src/config/logging.conf
environment:
  name: train-env
  version: 11
  docker:
    image: mcr.microsoft.com/azureml/base:latest # Confirm this is the correct Docker image
  conda_file: ./src/training/train-env.yml # Ensure this path is correct and the file exists
  python:
    user_managed_dependencies: false
compute:
  target: azureml:trainComputeCluster
# inputs:
#   your_input_name:
#     type: uri_folder
#     path: azureml:your-dataset-name@latest  # Specify your input dataset
# outputs:
#   your_output_name:
#     type: uri_folder
#     path: azureml://datastores/workspaceblobstore/paths/your/output/path  # Specify your output path
